default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: dantito32
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: crazy4cats_development

test:
  <<: *default
  database: crazy4cats_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
